spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/YLife/hello-spring-cloud
          search-paths: spring-cloud-config/repo
          username: YLife
          password: yl635901

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/