spring:
  application:
    name: hello-spring-cloud-consumer

server:
  port: 8765

feign:
  hystrix:
    enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
