spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: git@github.com:YLife/hello-spring-cloud.git
          search-paths: spring-cloud-config/respo
          username:
          password: 

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
